spring.application.name=payment-consumer-processor
server.port=8081

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BROKER:localhost:9092}
spring.kafka.topic=${KAFKA_TOPIC:payments}
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:payment-processor-group}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:payment_db}
spring.datasource.username=${POSTGRES_USER:payment}
spring.datasource.password=${POSTGRES_PASSWORD:payment123}
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
