spring.application.name=payment-producer
server.port=8080

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BROKER:localhost:9092}
spring.kafka.topic=${KAFKA_TOPIC:payments}
spring.kafka.topic-partitions=${KAFKA_PARTITIONS:3}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.properties.partitioner.class=org.apache.kafka.clients.producer.internals.DefaultPartitioner

# Auto Event Configuration
enable.auto.events=${ENABLE_AUTO_EVENTS:false}
